import Head from 'next/head'
import '../../config/i18n';
import { useTranslation } from 'react-i18next';
import { ButtonType } from '../../types';
import Page from '../../layouts/Page';
import SbChapter from '../../components/SbChapter/SbChapter';
import SbButton from '../../components/SbButton/SbButton';
import SbTitle from '../../components/SbTitle/SbTitle';
import { SbNameForm } from '../../components/SbNameForm/SbNameForm';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home() {
  const { t } = useTranslation();

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const router = useRouter()

  // eslint-disable-next-line react-hooks/rules-of-hooks
  useEffect(() => {
    if (window.tour) {
      router.reload()
    }
  })

  return (
    <div>
      <Head>
        <title>Geoguessing Schloss Benrath</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page
        title={t('castleOfBenrath')}
        subtitle={
          <SbTitle />
        }
      >
        <SbChapter title={t('register.chooseName')} text={t('register.chooseNameHint')}>
          <SbNameForm />
        </SbChapter>

        <SbButton buttonType={ButtonType.Primary} href="/tour">{ t('continue') }</SbButton>
      </Page>
    </div>
  )
}
