import Head from 'next/head'
import SbButton from '../components/SbButton/SbButton';
import SbIcon from '../components/SbIcon/SbIcon';
import { ButtonType, IconNames } from '../types';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Moment.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Hello World
        <SbButton buttonType={ButtonType.Primary} onClick={() => console.log("Hello")}>Test</SbButton>

        <SbIcon icon={IconNames.Home} />
      </main>
    </div>
  )
}
