---
name: Continuous Integration
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: npm
      - run: npm install
      - run: npm run lint
      - run: npm run stylelint
      - run: npm run tsc
